[[actions]]
name = "Play"
path = "NovetusLauncher.exe"
sandbox = true

[[actions]]
name = "Play (Legacy Launcher. USE THIS IF YOU DON'T HAVE NET FRAMEWORK 4.0 INSTALLED.)"
path = "Novetus_launcher_legacy.bat"
console = true
sandbox = true